PolizasSI/Areas/Admin/Controllers/AdminAccesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class AdminAccesoController : Controller
    {
        // GET: Admin/AdminAcceso
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FormIndex()
        {
            return View();
        }
        public ActionResult Logout()
        {
           return Index();
            
        }

    }
}

PolizasSI/Areas/Admin/Controllers/AdminGruposController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Web.Mvc;


namespace PolizasSI.Areas.Admin.Controllers
{
    public class AdminGruposController : Controller
    {
        
        
        // GET: Admin/AdminGrupos
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FormIndex()
        {
            return View();
        }

    }
}

PolizasSI/Areas/Admin/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Admin/Categoria
        public ActionResult Index()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/ComponenteClienteTitularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class ComponenteClienteTitularController : Controller
    {
        // GET: Admin/ComponenteClienteTitular
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FormIndex()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/ComponentePolizasProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class ComponentePolizasProductoController : Controller
    {
        // GET: Admin/ComponentePolizasProducto
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FormIndex()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/ComponentesClienteCobranzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class ComponentesClienteCobranzaController : Controller
    {
        // GET: Admin/ComponentesClienteCobranza
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FormIndex()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/ComponentesClientesContratantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class ComponentesClientesContratantesController : Controller
    {
        // GET: Admin/ComponentesClientesContratantes
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FormIndex()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/ComponentesPolizasDocController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class ComponentesPolizasDocController : Controller
    {
        // GET: Admin/ComponentesPolizasDoc
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FormIndex()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/ComponentesPolizasPolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class ComponentesPolizasPolController : Controller
    {
        // GET: Admin/ComponentesPolizasPol
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FormIndex()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/ComponentesPolizasTipoDocController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class ComponentesPolizasTipoDocController : Controller
    {
        // GET: Admin/ComponentesPolizasDoc
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FormIndex()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/PolizaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class PolizaController : Controller
    {
        // GET: Admin/Poliza
        public ActionResult Index()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/PolizasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class PolizasController : Controller
    {
        // GET: Admin/Polizas
        public ActionResult Index()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class ProductosController : Controller
    {
        // GET: Admin/Productos
        public ActionResult Index()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/ReporteCobranzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class ReporteCobranzaController : Controller
    {
        // GET: Admin/ReporteCobranza
        public ActionResult Index()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Controllers/SubCategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolizasSI.Areas.Admin.Controllers
{
    public class SubCategoriaController : Controller
    {
        // GET: Admin/SubCategoria
        public ActionResult Index()
        {
            return View();
        }
    }
}

PolizasSI/Areas/Admin/Views/ComponentePolizasProducto/Index.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
            <ul class="nav nav-tabs">
                <li ><a data-toggle="tab" href="#home" onclick="location.href='@Url.Action("Index", "ComponentesPolizasTipoDoc")'">Tipo de Documentacion</a></li>
                <li><a data-toggle="tab" href="#menu1" onclick="location.href='@Url.Action("Index", "ComponentesPolizasPol")'">Polizas</a></li>
                <li class="active"><a data-toggle="tab" href="#menu2" onclick="location.href='@Url.Action("Index", "ComponentePolizasProducto")'">Productos</a></li>
                <li><a data-toggle="tab" href="#menu3" onclick="location.href='@Url.Action("Index", "ComponentesPolizasDoc")'">Documentacion</a></li>

            </ul><br />

            <div class="tab-content">
                <div class="col-md-10"></div>

                <input type="button" id="btnAgregar" class="btn btn-primary" value="Nuevo" onclick="location.href='@Url.Action("FormIndex", "ComponentePolizasProducto")'" />

                <div class="DivisorH"></div>
                <div id="home" class="tab-pane fade in active">


                </div>
                <div id="menu1" class="tab-pane fade">

                </div>
                <div id="menu2" class="tab-pane fade">

                </div>
                <div id="menu3" class="tab-pane fade">

                </div>

            </div>

        </div>

        <div class="panel-body">
            <div class="col-md-12">
                <table class="table table-striped table-bordered table-hover dataTables-example">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Producto</th>
                            <th>Compuesto</th>
                            <th>Accion</th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr class="gradeX">
                            <td>Trident</td>
                            <td>
                                Internet
                                Explorer 4.0
                            </td>
                            <td>Win 95+</td>
                            <td class="center">
                                <button data-ajax="true" id="btnVer" type="submit" class="btn btn-primary">Ver</button>
                                <button data-ajax="true" id="btnEditar" type="submit" class="btn btn-primary">Editar </button>
                                <button data-ajax="true" id="btnEliminar" type="submit" class="btn btn-primary">Eliminar</button>
                            </td>
                            

                        </tr>
                        <tr class="gradeC">
                            <td>Trident</td>
                            <td>
                                Internet
                                Explorer 5.0
                            </td>
                            <td>Win 95+</td>
                            <td class="center">
                                <button data-ajax="true" id="btnVer" type="submit" class="btn btn-primary">Ver</button>
                                <button data-ajax="true" id="btnEditar" type="submit" class="btn btn-primary">Editar </button>
                                <button data-ajax="true" id="btnEliminar" type="submit" class="btn btn-primary">Eliminar</button>
                            </td>
                            

                        </tr>
                        <tr class="gradeA">
                            <td>Trident</td>
                            <td>
                                Internet
                                Explorer 5.5
                            </td>
                            <td>Win 95+</td>
                            <td class="center">
                                <button data-ajax="true" id="btnVer" type="submit" class="btn btn-primary">Ver</button>
                                <button data-ajax="true" id="btnEditar" type="submit" class="btn btn-primary">Editar </button>
                                <button data-ajax="true" id="btnEliminar" type="submit" class="btn btn-primary">Eliminar</button>
                            </td>
                           

                        </tr>
                        <tr class="gradeA">
                            <td>Trident</td>
                            <td>
                                Internet
                                Explorer 6
                            </td>
                            <td>Win 98+</td>
                            <td class="center">
                                <button data-ajax="true" id="btnVer" type="submit" class="btn btn-primary">Ver</button>
                                <button data-ajax="true" id="btnEditar" type="submit" class="btn btn-primary">Editar </button>
                                <button data-ajax="true" id="btnEliminar" type="submit" class="btn btn-primary">Eliminar</button>
                            </td>
                           

                        </tr>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<script>
        $(document).ready(function () {
            $('.dataTables-example').dataTable({
                responsive: true,
                "dom": 'T<"clear">lfrtip',
                "tableTools": {
                    "sSwfPath": "js/copy_csv_xls_pdf.swf"
                }
            });

            /* Init DataTables */
            //var oTable = $('#editable').dataTable();

            /* Apply the jEditable handlers to the table */
            //oTable.$('td').editable( '../example_ajax.php', {
            //    "callback": function( sValue, y ) {
            //        var aPos = oTable.fnGetPosition( this );
            //        oTable.fnUpdate( sValue, aPos[0], aPos[1] );
            //    },
            //    "submitdata": function ( value, settings ) {
            //        return {
            //            "row_id": this.parentNode.getAttribute('id'),
            //            "column": oTable.fnGetPosition( this )[2]
            //        };
            //    },

            //    "width": "90%",
            //    "height": "100%"
            //} );


        });

        //function fnClickAddRow() {
        //    $('#editable').dataTable().fnAddData( [
        //        "Custom row",
        //        "New row",
        //        "New row",
        //        "New row",
        //        "New row" ] );

        //}
</script>

PolizasSI/Areas/Admin/Views/ComponentesPolizasDoc/Index.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
            <ul class="nav nav-tabs">
                <li><a data-toggle="tab" href="#home" onclick="location.href='@Url.Action("Index", "ComponentesPolizasTipoDoc")'">Tipo de Documentacion</a></li>
                <li><a data-toggle="tab" href="#menu1" onclick="location.href='@Url.Action("Index", "ComponentesPolizasPol")'">Polizas</a></li>
                <li><a data-toggle="tab" href="#menu2" onclick="location.href='@Url.Action("Index", "ComponentePolizasProducto")'">Productos</a></li>
                <li class="active"><a data-toggle="tab" href="#menu3" onclick="location.href='@Url.Action("Index", "ComponentesPolizasDoc")'">Documentacion</a></li>

            </ul><br />

            <div class="tab-content">
                <div class="col-md-10"></div>

                <input type="button" id="btnAgregar" class="btn btn-primary" value="Nuevo" onclick="location.href='@Url.Action("FormIndex", "ComponentesPolizasDoc")'" />

                <div class="DivisorH"></div>
                <div id="home" class="tab-pane fade in active">


                </div>
                <div id="menu1" class="tab-pane fade">

                </div>
                <div id="menu2" class="tab-pane fade">

                </div>
                <div id="menu3" class="tab-pane fade">

                </div>

            </div>

        </div>

        <div class="panel-body">
            <div class="col-md-12">
                <table class="table table-striped table-bordered table-hover dataTables-example">
                    <thead>
                        <tr>
                            <th>Num</th>
                            <th>Titular</th>
                            <th>Tipo</th>
                            <th>Documento</th>
                            <th>Activa</th>
                            <th>Accion</th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr class="gradeX">
                            <td>Trident</td>
                            <td>
                                Internet
                                Explorer 4.0
                            </td>
                            <td>Win 95+</td>
                            <td class="center">4</td>
                            <td class="center">X</td>
                            <td class="center">
                                <button data-ajax="true" id="btnVer" type="submit" class="btn btn-primary">Ver</button>
                                <button data-ajax="true" id="btnEditar" type="submit" class="btn btn-primary">Editar </button>
                                <button data-ajax="true" id="btnEliminar" type="submit" class="btn btn-primary">Eliminar</button>
                            </td>                      

                        </tr>
                        <tr class="gradeC">
                            <td>Trident</td>
                            <td>
                                Internet
                                Explorer 5.0
                            </td>
                            <td>Win 95+</td>
                            <td class="center">5</td>
                            <td class="center">C</td>
                            <td class="center">
                                <button data-ajax="true" id="btnVer" type="submit" class="btn btn-primary">Ver</button>
                                <button data-ajax="true" id="btnEditar" type="submit" class="btn btn-primary">Editar </button>
                                <button data-ajax="true" id="btnEliminar" type="submit" class="btn btn-primary">Eliminar</button>
                            </td>
                          

                        </tr>
                        <tr class="gradeA">
                            <td>Trident</td>
                            <td>
                                Internet
                                Explorer 5.5
                            </td>
                            <td>Win 95+</td>
                            <td class="center">5.5</td>
                            <td class="center">A</td>
                            <td class="center">
                                <button data-ajax="true" id="btnVer" type="submit" class="btn btn-primary">Ver</button>
                                <button data-ajax="true" id="btnEditar" type="submit" class="btn btn-primary">Editar </button>
                                <button data-ajax="true" id="btnEliminar" type="submit" class="btn btn-primary">Eliminar</button>
                            </td>
                        

                        </tr>
                        <tr class="gradeA">
                            <td>Trident</td>
                            <td>
                                Internet
                                Explorer 6
                            </td>
                            <td>Win 98+</td>
                            <td class="center">6</td>
                            <td class="center">A</td>
                            <td class="center">
                                <button data-ajax="true" id="btnVer" type="submit" class="btn btn-primary">Ver</button>
                                <button data-ajax="true" id="btnEditar" type="submit" class="btn btn-primary">Editar </button>
                                <button data-ajax="true" id="btnEliminar" type="submit" class="btn btn-primary">Eliminar</button>
                            </td>
                        </tr>

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<script>
        $(document).ready(function () {
            $('.dataTables-example').dataTable({
                responsive: true,
                "dom": 'T<"clear">lfrtip',
                "tableTools": {
                    "sSwfPath": "js/copy_csv_xls_pdf.swf"
                }
            });

            /* Init DataTables */
            //var oTable = $('#editable').dataTable();

            /* Apply the jEditable handlers to the table */
            //oTable.$('td').editable( '../example_ajax.php', {
            //    "callback": function( sValue, y ) {
            //        var aPos = oTable.fnGetPosition( this );
            //        oTable.fnUpdate( sValue, aPos[0], aPos[1] );
            //    },
            //    "submitdata": function ( value, settings ) {
            //        return {
            //            "row_id": this.parentNode.getAttribute('id'),
            //            "column": oTable.fnGetPosition( this )[2]
            //        };
            //    },

            //    "width": "90%",
            //    "height": "100%"
            //} );


        });

        //function fnClickAddRow() {
        //    $('#editable').dataTable().fnAddData( [
        //        "Custom row",
        //        "New row",
        //        "New row",
        //        "New row",
        //        "New row" ] );

        //}
</script>

PolizasSI/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    Layout = null;
    string controlador = ViewContext.RouteData.Values["Controller"].ToString().ToLower();
    //Model.Entities.Usuario usuario = controlador == "login" ? new Model.Entities.Usuario()
    // : new Model.BussinesLogic.UsuarioLogic().Obtener(SessionHelper.GetUser());
}
<!DOCTYPE html>
<html lang="es">
<head>
    @*<title>@ViewBag.Title </title>*@
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <link href="~/Areas/Admin/Assets/css/admin-style.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Assets/css/Site.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Assets/css/bootstrap.theme.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Areas/Admin/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Assets/css/datepicker3.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Assets/js/jquery-ui-1.11.4.custom/jquery-ui.min.css" rel="stylesheet" />
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.css" rel="stylesheet">
    <link href="~/Areas/Admin/assets/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="~/Areas/Admin/assets/css/dataTables.responsive.css" rel="stylesheet" />
    <link href="~/Areas/Admin/assets/css/dataTables.tableTools.min.css" rel="stylesheet" />
    <script src="~/Areas/Admin/Assets/js/jquery.js"></script>
    <script src="~/Areas/Admin/assets/js/summernote.js"></script>

    <script src="~/Areas/Admin/Assets/js/jquery-ui-1.11.4.custom/jquery-ui.min.css"></script>

</head>
<body>

    @*@if (controlador != "login")
        {*@
    @*<nav class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        Polizas Soluciones Instantáneas  V 1.0.0
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->

                <div class="collapse navbar-collapse" id="menu">
                    <ul class="nav navbar-nav">
                        @{
                            var categorias = new Model.BussinesLogic.CategoriaLogic().ObtenerPor(-1).OrderBy(x => x.Orden);
                                foreach (var e in categorias)
                                {
                                    <li>
                                        <a href="~/admin/contenido/?Tipo=@e.idCategoria">@e.Titulo</a>
                                    </li>
                                }
                        }
                        <li>
                            <a href="">Inicio</a>
                        </li>
                        <li>
                            <a href="">Usuarios</a>
                        </li>
                        <li>
                            <a href="">Componentes</a>
                        </li>

                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <img id="user-pic" src="~/Uploads/@usuario.Foto" />
                                    <b>Hola</b>, @usuario.Nombre <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="~/">Ver Página</a>
                                </li>
                                <li>

                                </li>
                                <li>
                                    <a href="~/admin/login/logout">Finalizar Sesión</a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                </div><!-- /.navbar-collapse -->


            </div>
            <!-- /.container-fluid -->
        </nav>

        }*@


    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Polizas Soluciones Instantáneas  V 1.0.0</a>
            </div>

            <ul class="nav navbar-nav">
                <li><a href=""></a></li>
                <li><a href=""></a></li>
                <li class="active"><a href="#">Inicio</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Usuarios
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"onclick="location.href='@Url.Action("Index", "AdminAcceso")'">Administrador de Accesos</a></li>
                        <li><a href="#"onclick="location.href='@Url.Action("Index", "AdminGrupos")'">Grupos</a></li>
                        <li><a href="#">Permisos</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a id="dLabel" role="button" data-toggle="dropdown" data-target="#">
                        Componentes <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                        <li class="dropdown-submenu">
                            <a tabindex="-1" href="#"onclick="location.href='@Url.Action("Index", "ComponentesClientesContratantes")'">Clientes</a>
                            <ul class="dropdown-menu">
                                <li><a tabindex="-1" href="#"onclick="location.href='@Url.Action("Index", "ComponentesClientesContratantes")'">Contratante</a></li>
                                <li><a tabindex="-1" href="#"onclick="location.href='@Url.Action("Index", "ComponenteClienteTitular")'">Titular</a></li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu">
                            <a tabindex="-1" href="#"onclick="location.href='@Url.Action("Index", "ComponentesPolizasTipoDoc")'">Polizas</a>
                            <ul class="dropdown-menu">
                                <li><a tabindex="-1" href="#"onclick="location.href='@Url.Action("Index", "ComponentesPolizasTipoDoc")'">Tipo de Documentacion</a></li>
                                <li><a tabindex="-1" href="#"onclick="location.href='@Url.Action("Index", "ComponentesPolizasPol")'">Polizas</a></li>
                                <li><a tabindex="-1" href="#"onclick="location.href='@Url.Action("Index", "ComponentePolizasProducto")'">Productos</a></li>
                                <li><a tabindex="-1" href="#"onclick="location.href='@Url.Action("Index", "ComponentesPolizasDoc")'">Documentación</a></li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu">
                            <a tabindex="-1" href="#"onclick="location.href='@Url.Action("Index", "ComponentesClienteCobranza")'">Cobranza</a>
                            <ul class="dropdown-menu">
                                <li><a tabindex="-1" href="#" onclick="location.href='@Url.Action("Index", "ComponentesClienteCobranza")'">Reporte de Cobranza</a></li>
                            </ul>
                        </li>
                    </ul>
                    </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                @RenderBody()
            </div>
        </div>

        <div class="well text-center">
            <div class="">Desarrollado por <a target="_blank" href="http://solucionesinstantaneas.com/">Soluciones Instantáneas</a></div>
        </div>
    </div>

        
            <hr>
           

          
 

    <script src="~/Areas/Admin/Assets/js/bootstrap.min.js"></script>
    <script src="~/Areas/Admin/Assets/js/jquery-ui-1.11.4.custom/jquery-ui.min.js"></script>
    <script src="~/Areas/Admin/Assets/js/jquery.form.js"></script>
    <script src="~/Areas/Admin/Assets/js/jquery.dataTables.min.js"></script>
    <script src="~/Areas/Admin/assets/js/dataTables.bootstrap.js"></script>
    <script src="~/Areas/Admin/assets/js/jquery.dataTables.js"></script>
    <script src="~/Areas/Admin/Assets/js/ini.js"></script>
    <script src="~/Areas/Admin/assets/js/dataTables.responsive.js"></script>
    <script src="~/Areas/Admin/Assets/js/jquery.anexgrid.min.js"></script>
    <script src="~/Areas/Admin/Assets/js/jquery.validate.min.js"></script>
    <script src="~/Areas/Admin/Assets/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Areas/Admin/assets/js/dataTables.tableTools.min.js"></script>
</body>
</html>


<script>

    $(document).ready(function () {
        $('.dropdown a.test').on("click", function (e) {
            $(this).next('ul').toggle();
            e.stopPropagation();
            e.preventDefault();
        });
    });

</script>